# Generated by Django 4.2.24 on 2025-10-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'لیست پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='تصویر پروژه')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='aboutus.project', verbose_name='لیست پروژه ها')),
            ],
        ),
    ]
