# Generated by Django 4.2.24 on 2025-10-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='تصویر پروژه'),
        ),
    ]
