# Generated by Django 4.2.24 on 2025-10-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'تصویر پروژه', 'verbose_name_plural': 'لیست تصاویر پروژه'},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectImage', to='aboutus.project', verbose_name='لیست پروژه ها'),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectDetail', to='aboutus.project', verbose_name='لیست پروژه ها')),
            ],
            options={
                'verbose_name': 'جزعیات پروژه',
                'verbose_name_plural': 'لیست جزعیات پروژه',
            },
        ),
    ]
