# Generated by Django 4.2.24 on 2025-10-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_alter_projectimage_options_projectimage_createddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Fetaure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('aboutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='aboutus.aboutus', verbose_name='درباره ما')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'لیست تصاویر ویژگی',
            },
        ),
    ]
