# Generated by Django 4.2.24 on 2025-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_aboutus_fetaure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetaure',
            name='aboutus',
        ),
        migrations.AddField(
            model_name='fetaure',
            name='aboutus',
            field=models.ManyToManyField(related_name='feature', to='aboutus.aboutus', verbose_name='درباره ما'),
        ),
    ]
