# Generated by Django 4.2.24 on 2025-10-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_remove_fetaure_aboutus_fetaure_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetaure',
            name='aboutus',
        ),
        migrations.AddField(
            model_name='fetaure',
            name='aboutus',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='aboutus.aboutus', verbose_name='درباره ما'),
            preserve_default=False,
        ),
    ]
