# Generated by Django 4.2.24 on 2025-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_remove_fetaure_aboutus_fetaure_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=12, upload_to='', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
