# Generated by Django 4.2.24 on 2025-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.ImageField(upload_to='', verbose_name='آیکون')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
        ),
    ]
