# Generated by Django 4.2.27 on 2025-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='وضعیت اعتبارسنجی'),
        ),
    ]
