# Generated by Django 4.2.24 on 2025-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='describtion',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=11, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
