# Generated by Django 4.2.27 on 2025-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_remove_contactus_describtion_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='type',
            field=models.CharField(choices=[('contact', 'تماس با ما'), ('supoort', 'پشتیبانی'), ('consultation', 'درخواست مشاوره')], default='contact', max_length=20, verbose_name='نوع درخواست'),
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='Contact',
        ),
    ]
