# Generated by Django 4.2.24 on 2025-10-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='blog.blog', verbose_name='بلاگ'),
        ),
    ]
